# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('tweets_count', models.IntegerField(blank=True, default=0, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=5000, null=True)),
                ('retweet_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('retweet_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('screen_name', models.CharField(blank=True, default=b'', max_length=500, null=True)),
                ('followers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, default=b'', max_length=500, null=True)),
                ('centrality', models.FloatField(blank=True, default=0.0, null=True)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='_user_followers_+', to='mole.User')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.User'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.Project'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='trend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.Trend'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mole.Project'),
        ),
    ]
