# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0004_urls_urlsgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('centrality', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
