# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0006_centralityhashtag_hashtag_hashtaggraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
