# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0007_hashtag_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
