# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mole', '0009_auto_20160820_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
